before:
  hooks:
    - go mod download
builds:
  - id: klogs
    main: .
    binary: klogs
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm: [6, 7]
archives:
  - id: klogs-archive
    name_template: |-
      klogs_{{ .Tag }}_{{ .Os }}_{{ .Arch -}}
      {{- with .Arm -}}
        {{- if (eq . "6") -}}hf
        {{- else -}}v{{- . -}}
        {{- end -}}
      {{- end -}}
    builds:
      - klogs
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files: ["LICENSE"]
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
